###################################
########## ENCODER SETTINGS #######
###################################

## SIZE OF A PDF FILE
# height of the A4 PDF, in milimeters
PDF_H = 297
PDF_W = 210


## BORDERS AND QR CODE
# set dimensions for PDF markers and offesets
PDF_BORDER_OFFSET = 8
QR_CODE_SIZE = 30
# Probability of a unit square (1x1) to be black
# in the borders of the form
SQUARE_GRID_BLACK_SQUARE_PROBABILITY = 0.6
# pixels per unit square of the border grid
BORDER_PX_PER_SQUARE = 1.5
# number of squares on the long and short edges of the markers
BORDER_LONG_EDGE_SQUARE = 20
BORDER_SHORT_EDGE_SQUARE = 7
# size of the border in pixels
BORDER_LONG_EDGE_PX = BORDER_PX_PER_SQUARE * BORDER_LONG_EDGE_SQUARE
BORDER_SHORT_EDGE_PX = BORDER_PX_PER_SQUARE * BORDER_SHORT_EDGE_SQUARE

## TITLE
# set dimension for the maximal width of the title on the PDF
TITLE_FONT = "helvetica"
TITLE_FONT_SIZE = 36
PDF_TITLE_X_POSITION = PDF_BORDER_OFFSET + BORDER_SHORT_EDGE_PX + 5
PDF_TITLE_Y_POSITION = PDF_BORDER_OFFSET + BORDER_SHORT_EDGE_PX + 5

## QUESTIONS
# settings for the questions
PDF_QUESTION_TITLE_AFTER_OFFSET = 1
PDF_QUESTION_BETWEEN_OFFSET = 7

PDF_DETAILS_AFTER_OFFSET = 2
PDF_DETAILS_BETWEEN_OFFSET = 5
PDF_DETAILS_LEFT_PADDING = 15
PDF_DETAILS_MAX_LENGTH = 170

PDF_SQUARES_AFTER_OFFSET = 7
PDF_ANSWER_SQUARE_X_MIN = PDF_BORDER_OFFSET + BORDER_SHORT_EDGE_PX + 5
PDF_ANSWER_SQUARE_X_MAX = PDF_W - PDF_ANSWER_SQUARE_X_MIN
PDF_ANSWER_SQUARE_SIZE = 8


QUESTION_TITLE_FONT = "helvetica"
QUESTION_TITLE_FONT_SIZE = 20
QUESTION_DETAILS_FONT = "helvetica"
QUESTION_DETAILS_FONT_SIZE = 15
QUESTION_MULTIPLE_CHOICE_OPTION_FONT = "helvetica"
QUESTION_MULTIPLE_CHOICE_OPTION_FONT_SIZE = 15
QUESTION_MULTIPLE_CHOICE_OPTION_BETWEEN_SIZE = 5

PDF_MAXIMAL_PAGE_HEIGHT = 250


###################################
########## DECODER SETTINGS #######
###################################

MARKER_MATCHING_TOLERANCE = 1.3
IMAGE_BLACK_THRESHOLD = 60
POLYGON_APROXIMATION_EPSILON = 0.03

# Probability of a unit square (1x1) to be black
# in the borders of the form
SQUARE_GRID_BLACK_SQUARE_PROBABILITY = 0.6
