name: 'Conda Environment'
description: 'Builds the SmartForms conda environment from the  .yaml file'

runs:
  using: composite
  steps:
  - name: Cook environment
    shell: bash
    uses: conda-incubator/setup-miniconda@v2
    with: 
      activate-environment: SmartForms
      environment-file: conda_environment.yaml
      auto-activate-base: false
