name: 'Prepare Environment'
description: 'Installs and activates the conda environment "SmartForms"'

runs:
  using: composite
  steps:
  - uses: conda-incubator/setup-miniconda@v2
    with: 
      activate-environment: SmartForms
      environment-file: conda_environment.yaml
      auto-activate-base: false
