name: 'Prepare Environment'
description: 'BCheckouts, installs and activates the conda environment "SmartForms"'

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Cook environment
    shell: bash
    uses: conda-incubator/setup-miniconda@v2
    with: 
      activate-environment: SmartForms
      environment-file: conda_environment.yaml
      auto-activate-base: false
