# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Backend Unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'Merge pull request #')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install -y libzbar0
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r backend/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      env:
        MONGO_USER: ${{ secrets.MONGO_USER }} 
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        COOKIES_SECRET: ${{ secrets.COOKIES_SECRET }}
        USER_AUTHENTICATION_CHECKS_ENABLED: 'False'
      run: |
        (cd backend/sources/tests/ && python -m unittest)