name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build

    environment: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/Prep-Env

      - run: conda info

      - name: Build
        uses: ./.github/actions/Build

  test:
    name: Test

    needs: Build

    environment: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/Prep-Env

      - run: conda info

      - name: Test
        uses: ./.github/actions/Test
