name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      run: |
        echo "helo 1"

      - name: Setup conda environment
      - uses: conda-incubator/setup-miniconda@v2
        with: 
          activate-environment: SmartForms
          environment-file: conda_environment.yml
          auto-activate-base: false

      run: |
        echo "helo 2"

      - name: Build
      run: |
        make build

      - name: Test
      run: |
        make test-ci
