name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build and Test

    environment: CI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: ls files
        run: |
          ls -la

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with: 
          activate-environment: SmartForms
          environment-file: conda_environment.yml
          auto-activate-base: false

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test-ci
