name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            label: Linux-64
            prefix: /usr/share/miniconda3/envs/my-env

    name: Build & Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        uses: ./.github/actions/Prep-Env

      - name: Cheeck Conda Env
        run: |
          conda info

      - name: Build
        uses: ./.github/actions/Build

      - name: Test
        uses: ./.github/actions/Test

  deploy:
    defaults:
      run:
        shell: bash -l {0}

    name: Deploy to production

    needs: build-test
 
    environment: Production
    runs-on: ubuntu-20.04

    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Add Known Hosts
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan smartforms.ml >> /home/runner/.ssh/known_hosts

      - name: Add SSH Key & Push
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/deployer
          chmod 600 /home/runner/.ssh/deployer
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/deployer
          ssh-add -l 

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git remote add production deployer@smartforms.ml:/home/deployer/Production/SmartForms-GitBare/smart-forms.git
          git push production main -f
