name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    environment: CI

    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
      - uses: ./.github/actions/Prep-Env

      - uses: ./.github/actions/Build

      - uses: ./.github/actions/Test

  deploy:
    name: Deploy to production

    needs: build-test
 
    environment: Production
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v.0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push to production
        run: |
          git remote add production ssh://deployer@smartforms.ml:22/home/deployer/Production/SmartForms-GitBare/smart-forms.git
          git push production main
