name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: Linux-64
            prefix: /usr/share/miniconda3/envs/my-env

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        uses: ./.github/actions/Prep-Env

      - name: Build
        uses: ./.github/actions/Build

      - name: Test
        uses: ./.github/actions/Test

  deploy:
    name: Deploy to production

    # needs: build-test
 
    environment: Production
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Known Hosts
        run: |
          ssh-keyscan smartforms.ml >> /home/runner/.ssh/known_hosts

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push to production
        run: |
          git remote add production ssh://deployer@smartforms.ml:22/home/deployer/Production/SmartForms-GitBare/smart-forms.git
          git push production main
