name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged

    defaults:
      run:
        shell: bash -l {0}

    name: Deploy to production

    needs: build-test
 
    environment: Production
    runs-on: ubuntu-20.04

    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
      - name: Checkout
        # if: github.event.pull_request.merged
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Add Known Hosts
        # if: github.event.pull_request.merged
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan smartforms.ml >> /home/runner/.ssh/known_hosts

      - name: Add SSH Key & Push
        # if: github.event.pull_request.merged
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/deployer
          chmod 600 /home/runner/.ssh/deployer
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/deployer
          ssh-add -l 

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git remote add production deployer@smartforms.ml:/home/deployer/Production/SmartForms-GitBare/smart-forms.git
          git push production main -f
